# Generated by Django 3.2.20 on 2023-07-17 11:59

from django.db import migrations, models
import schoolify.auth_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentCooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('school_subject', models.CharField(choices=[('Mathematics', 'Mathematics'), ('English', 'English'), ('Music', 'Music'), ('Cooking', 'Cooking')], max_length=20)),
                ('assignment_name', models.TextField(verbose_name='Name of assignment')),
                ('recipe_name', models.TextField()),
                ('dish_image', models.ImageField(upload_to='', validators=[schoolify.auth_app.validators.image_size_validator_10mb])),
                ('ingredients', models.TextField()),
                ('preparation_time', models.TimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssignmentEnglish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('school_subject', models.CharField(choices=[('Mathematics', 'Mathematics'), ('English', 'English'), ('Music', 'Music'), ('Cooking', 'Cooking')], max_length=20)),
                ('assignment_name', models.TextField(verbose_name='Name of assignment')),
                ('essay', models.TextField()),
                ('external_resources_used', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssignmentMathematics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('school_subject', models.CharField(choices=[('Mathematics', 'Mathematics'), ('English', 'English'), ('Music', 'Music'), ('Cooking', 'Cooking')], max_length=20)),
                ('assignment_name', models.TextField(verbose_name='Name of assignment')),
                ('solution', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssignmentMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('school_subject', models.CharField(choices=[('Mathematics', 'Mathematics'), ('English', 'English'), ('Music', 'Music'), ('Cooking', 'Cooking')], max_length=20)),
                ('assignment_name', models.TextField(verbose_name='Name of assignment')),
                ('song', models.FileField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
