# Generated by Django 3.2.20 on 2023-07-19 17:59

from django.db import migrations, models
import schoolify.auth_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentcooking',
            name='dish_image',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[schoolify.auth_app.validators.image_size_validator_10mb]),
        ),
    ]
