# Generated by Django 3.2.20 on 2023-07-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_auto_20230720_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentmusic',
            name='song',
            field=models.FileField(help_text='Please upload a record of your song here', upload_to='mediafiles/'),
        ),
    ]
