# Generated by Django 3.2.20 on 2023-07-26 08:53

from django.db import migrations, models
import schoolify.auth_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_alter_assignmentmusic_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentcooking',
            name='dish_image',
            field=models.ImageField(blank=True, help_text='Please upload a picture of your dish.', null=True, upload_to='dishes', validators=[schoolify.auth_app.validators.image_size_validator_10mb]),
        ),
        migrations.AlterField(
            model_name='assignmentmusic',
            name='song',
            field=models.FileField(help_text='Please upload a record of your song here', upload_to='songs'),
        ),
    ]
