# Generated by Django 3.2.20 on 2023-08-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0008_alter_assignmentmathematics_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentcooking',
            name='school_subject',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('English', 'English'), ('Music', 'Music'), ('Cooking', 'Cooking')], max_length=11),
        ),
        migrations.AlterField(
            model_name='assignmentenglish',
            name='school_subject',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('English', 'English'), ('Music', 'Music'), ('Cooking', 'Cooking')], max_length=11),
        ),
        migrations.AlterField(
            model_name='assignmentmathematics',
            name='school_subject',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('English', 'English'), ('Music', 'Music'), ('Cooking', 'Cooking')], max_length=11),
        ),
        migrations.AlterField(
            model_name='assignmentmusic',
            name='school_subject',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('English', 'English'), ('Music', 'Music'), ('Cooking', 'Cooking')], max_length=11),
        ),
    ]
