# Generated by Django 3.2.20 on 2023-08-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0009_auto_20230808_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentcooking',
            name='preparation_time',
            field=models.DurationField(help_text='Please fill in the full reparation time, together with cooking time.'),
        ),
    ]
