# Generated by Django 3.2.20 on 2023-08-16 12:42

from django.db import migrations, models
import schoolify.assignment.validators


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0010_alter_assignmentcooking_preparation_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentcooking',
            options={'verbose_name_plural': 'Assignment cooking'},
        ),
        migrations.AlterModelOptions(
            name='assignmentenglish',
            options={'verbose_name_plural': 'Assignment english'},
        ),
        migrations.AlterModelOptions(
            name='assignmentmathematics',
            options={'verbose_name_plural': 'Assignment mathematics'},
        ),
        migrations.AlterField(
            model_name='assignmentcooking',
            name='dish_image',
            field=models.ImageField(blank=True, help_text='Please upload a picture of your dish.', null=True, upload_to='dishes', validators=[schoolify.assignment.validators.image_size_validator_10mb]),
        ),
    ]
