# Generated by Django 3.2.20 on 2023-07-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('author', models.TextField(max_length=25)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('school_subject', models.CharField(choices=[('Mathematics', 'Mathematics'), ('English', 'English'), ('Music', 'Music'), ('Cooking', 'Cooking')], max_length=20)),
                ('number_of_pages', models.IntegerField(blank=True, null=True)),
                ('available_from', models.DateField()),
            ],
        ),
    ]
