# Generated by Django 3.2.20 on 2023-07-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
