# Generated by Django 3.2.20 on 2023-07-12 17:00

from django.db import migrations
import schoolify.auth_app.managers


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
                ('objects', schoolify.auth_app.managers.AppUserManager()),
            ],
        ),
    ]
