# Generated by Django 3.2.20 on 2023-07-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_appuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='school_grade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
