# Generated by Django 3.2.20 on 2023-07-31 15:59

from django.db import migrations, models
import schoolify.auth_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=35, validators=[schoolify.auth_app.validators.validate_capitalized]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=35, validators=[schoolify.auth_app.validators.validate_capitalized]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile-pictures', validators=[schoolify.auth_app.validators.image_size_validator_10mb]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school_grade',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[schoolify.auth_app.validators.validate_school_year_range]),
        ),
    ]
