# Generated by Django 3.2.20 on 2023-08-11 07:25

from django.db import migrations, models
import schoolify.auth_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='personal_number',
            field=models.BigIntegerField(unique=True, validators=[schoolify.auth_app.validators.validate_len_personal_number]),
        ),
    ]
