# Generated by Django 3.2.20 on 2023-08-11 07:29

import django.core.validators
from django.db import migrations, models
import schoolify.auth_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_alter_appuser_personal_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='personal_number',
            field=models.BigIntegerField(unique=True, validators=[schoolify.auth_app.validators.validate_len_personal_number, django.core.validators.MaxValueValidator(9912319999)]),
        ),
    ]
